version: '3.8'
services:
  db:
    image: postgres:12.4
    restart: always
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    restart: always
    build:
      context: ../backend
    expose:
      - 8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    build:
      context: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:
